name: bubo
description: A combinatorial parser library writtren in Dart.
version: 0.0.1
author: 'Eric De Wildt'
homepage: 'https://ericdw.github.io/bubo/'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.11.0

dev_dependencies:
  test:
  build_runner:
  freezed: ^0.11.4
