name: bubo
description: A combinatorial parser library writtren in Dart.
version: 0.0.1
author: 'Eric De Wildt'
homepage: ''

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  freezed_annotation:

dev_dependencies:
  test:
  build_runner:
  freezed:
